@startuml
 
!include https://raw.githubusercontent.com/patrik-csak/one-dark-plantuml-theme/v1.0.1/theme.puml
skinparam backgroundcolor #1E2021
skinparam linetype ortho

title Monochrome

struct MonochromeApp {
    var body
}

struct ContentView {
    - @State var size
    - @State var field
    - @State var gameStarted
    - @State var alertPresented
    
    - let minOpacity
    - let maxOpacity

    - let majorColor
    - let minorColor
    - let backgroundColor

    var body

    - startnewGame(withFieldSize)
}

struct FieldView {
    @Binding var field
    @Binding var alertPresented

    let majorColor
    let minorColor

    var body

    - changeColor(x, y)
    - checkGame()
}

protocol App
protocol Scene
protocol View

MonochromeApp --|> App
MonochromeApp --> Scene
MonochromeApp *-- ContentView

ContentView --|> View
ContentView *-- FieldView

FieldView --|> View


@enduml